### ISSUE TITLE
dev: incorrect `ETHEREUM_CONSENSUS_RPC_URL` in `.env.example

### ISSUE THREAD

**Issue by ftupas** [keep-starknet-strange/beerus#254]
### Issue

When setting up a new environment, `ETHEREUM_CONSENSUS_RPC_URL` is not in the right format which results in error on running the binaries

![image](https://user-images.githubusercontent.com/35031356/224317793-6f8a9c85-bcb2-4e6c-a6eb-f8c5f3d044f4.png)

### Solution

Modify `.env.example` file and update README to reference [helios](https://github.com/a16z/helios#configuration-files)

```toml
[mainnet]
consensus_rpc = "https://www.lightclientdata.org"
execution_rpc = "https://eth-mainnet.g.alchemy.com/v2/XXXXX"
checkpoint = "0x85e6151a246e8fdba36db27a0c7678a575346272fe978c9281e13a8b26cdfa68"

[goerli]
consensus_rpc = "http://testing.prater.beacon-api.nimbus.team"
execution_rpc = "https://eth-goerli.g.alchemy.com/v2/XXXXX"
checkpoint = "0xb5c375696913865d7c0e166d87bc7c772b6210dc9edf149f4c7ddc6da0dd4495"
```
